# Generated by Django 4.1.2 on 2022-10-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_post_user_alter_post_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='artist',
            new_name='artists',
        ),
    ]
