# Generated by Django 4.1.2 on 2022-10-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_rename_artist_post_artists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='artists',
            new_name='artist',
        ),
    ]
